#define INTERNAL_FUINCTION "<internal>"
#define INIT_FILENAME "<init>"
#define NOT_A_FUNCTION_ERR "not a function"
#define OUT_OF_TIMER_SLOTS_ERR "out of timer slots"
#define INVALID_TIMER_ID_ERR "invalid timer ID"
#define INVALID_CALLBACK_ERR "callback is not a function or string"
#define INVALID_DELAY_ERR "invalid delay"
#define INVALID_EVENT_ERR "not a supported event"
#define SEND_CALLED_ERR "send() has already been called"
#define OPEN_CALLED_ERR "open() has already been called"
#define OPEN_NOT_CALLED_ERR "open() has not been called"
#define EXISTING_REQUEST_ERR "HTTP request already in progress"
#define NOT_XMLHTTPREQUEST_ERR "Object is not a XMLHttpRequest"
#define CONSOLE_TO_STRING_TAG "Console"
#define XMLHTTPREQUEST_NAME "XMLHttpRequest"
